<?php
/** Template Name: Home */
defined('ABSPATH') || exit;
get_header();
$page=get_queried_object_id();
$sections=function_exists('noir_home_page')?noir_home_page($page):[];
$services=function_exists('noir_home_services')?noir_home_services($page):[];
$projects=function_exists('noir_project_placements')?noir_project_placements($page,'home'):[];
?>
<main id="main-content" class="home-main" tabindex="-1">
<?php if (!empty($sections['hero'])) : $hero=$sections['hero']; ?>
<section class="home-hero"><div class="container home-hero-inner">
<div class="home-meta"><p class="eyebrow"><?php echo esc_html($hero['badge']); ?></p><p class="small-label"><?php echo esc_html($hero['meta']); ?></p></div>
<div class="home-hero-grid"><div class="home-hero-copy"><p class="label accent"><?php echo esc_html($hero['eyebrow']); ?></p><h1><?php echo esc_html($hero['heading']); ?><?php if ($hero['accent']!=='') : ?><br><em class="accent"><?php echo esc_html($hero['accent']); ?></em><?php endif; ?><?php if ($hero['ending']!=='') : ?><br><?php echo esc_html($hero['ending']); ?><?php endif; ?></h1><p class="muted lead"><?php echo esc_html($hero['body']); ?></p><div class="final-actions"><?php noir_appointment_link(); $url=noir_theme_page_url('services'); if ($url) : ?><a class="button secondary" href="<?php echo esc_url($url); ?>"><?php esc_html_e('View Services','noir-auto-detailing'); ?> <span aria-hidden="true">→</span></a><?php endif; ?></div></div>
<?php if (!empty($hero['image']) && noir_image_valid($hero['image'])) : ?><figure class="home-hero-image"><?php echo wp_get_attachment_image($hero['image'],'large',false,['sizes'=>'(min-width: 1440px) 535px, (min-width: 1024px) 42vw, calc(100vw - 48px)','loading'=>'eager','fetchpriority'=>'high']); ?><?php if ($hero['caption']!=='') : ?><figcaption class="small-label"><?php noir_icon('verified'); echo esc_html($hero['caption']); ?></figcaption><?php endif; ?></figure><?php endif; ?></div>
<?php if (!empty($sections['trust'])) : ?><dl class="home-trust"><?php foreach ($sections['trust'] as $item) : ?><div><dt class="small-label"><?php echo esc_html($item['title']); ?></dt><dd><?php echo esc_html($item['value']); ?></dd><?php if ($item['body']!=='') : ?><dd class="muted"><?php echo esc_html($item['body']); ?></dd><?php endif; ?></div><?php endforeach; ?></dl><?php endif; ?>
</div></section>
<?php else : ?><section class="services-section container"><h1><?php the_title(); ?></h1><p><?php esc_html_e('Home information is currently unavailable. Please contact the Studio.','noir-auto-detailing'); ?></p><?php noir_public_contacts(); ?></section><?php endif; ?>
<?php if (!empty($sections['philosophy'])) : $section=$sections['philosophy']; ?><section class="services-section home-philosophy"><div class="container home-philosophy-grid"><div><p class="label accent"><?php echo esc_html($section['eyebrow']); ?></p><p class="muted"><?php esc_html_e('Studio Philosophy','noir-auto-detailing'); ?></p></div><div><h2><?php echo esc_html($section['heading']); ?><?php if ($section['accent']!=='') : ?><br><span class="accent"><?php echo esc_html($section['accent']); ?></span><?php endif; ?></h2><div class="home-philosophy-body"><p class="muted"><?php echo esc_html($section['body']); ?></p><?php if ($section['secondary']!=='') : ?><p class="muted"><?php echo esc_html($section['secondary']); ?></p><?php endif; ?></div><?php if ($section['items']) : ?><div class="home-standards"><?php foreach ($section['items'] as $item) { get_template_part('template-parts/home-benefit',null,['item'=>$item]); } ?></div><?php endif; ?></div></div></section><?php endif; ?>
<?php if ($services) : ?><section class="services-section home-services"><div class="container"><?php noir_section_heading($sections['services']); ?><div class="home-service-grid">
<?php foreach ($services as $service) : $links=noir_service_links($service['service_id']); ?><article class="home-service" data-home-service="<?php echo esc_attr($service['service_id']); ?>"><div class="home-service-image"><?php echo wp_get_attachment_image($service['image'],'large',false,['sizes'=>'(min-width: 1440px) 421px, (min-width: 1024px) 31vw, calc(100vw - 48px)','loading'=>'lazy','fetchpriority'=>'auto']); ?><?php if ($service['badge']!=='') : ?><p class="small-label accent"><?php echo esc_html($service['badge']); ?></p><?php endif; ?></div><div class="home-service-content"><h3><?php echo esc_html($service['title']); ?></h3><p class="muted"><?php echo esc_html($service['teaser']!==''?$service['teaser']:$service['short_description']); ?></p><dl class="home-service-facts">
<?php if ($service['scope']!=='') : ?><div><dt class="small-label"><?php esc_html_e('Service Scope','noir-auto-detailing'); ?></dt><dd><?php echo esc_html($service['scope']); ?></dd></div><?php endif; ?>
<?php if ($service['protection']!==null) : ?><div><dt class="small-label"><?php esc_html_e('Protection','noir-auto-detailing'); ?></dt><dd class="accent"><?php echo esc_html($service['protection']); ?></dd></div><?php endif; ?>
<?php get_template_part('template-parts/service-facts',null,['service'=>$service]); ?></dl><div class="home-service-links"><?php if ($links['detail']) : ?><a class="text-link" href="<?php echo esc_url($links['detail']); ?>"><?php esc_html_e('Explore Package','noir-auto-detailing'); ?> <span aria-hidden="true">→</span></a><?php endif; ?><?php if ($links['appointment']) : ?><a class="text-link small-label" href="<?php echo esc_url($links['appointment']); ?>"><?php esc_html_e('Request Appointment','noir-auto-detailing'); ?><span class="screen-reader-text"> — <?php echo esc_html($service['title']); ?></span></a><?php endif; ?></div></div></article><?php endforeach; ?>
</div></div></section><?php endif; ?>
<?php if ($projects) : ?><section class="services-section home-projects"><div class="container"><?php if (!empty($sections['projects'])) { noir_section_heading($sections['projects']); } ?><div class="home-project-grid"><?php foreach ($projects as $index=>$project) { get_template_part('template-parts/home-project',null,['project'=>$project,'featured'=>$index===0]); } ?></div></div></section><?php endif; ?>
<?php if (!empty($sections['benefits'])) : ?><section class="services-section home-benefits" aria-label="<?php esc_attr_e('Studio benefits','noir-auto-detailing'); ?>"><div class="container home-benefit-grid"><?php foreach ($sections['benefits'] as $item) { get_template_part('template-parts/home-benefit',null,['item'=>$item]); } ?></div></section><?php endif; ?>
<?php if (!empty($sections['testimonials']['items'])) : ?><section class="services-section home-testimonials"><div class="container"><?php noir_section_heading($sections['testimonials']); ?><div class="home-testimonial-grid"><?php foreach ($sections['testimonials']['items'] as $item) : ?><figure><p class="home-rating"><span class="screen-reader-text"><?php echo esc_html(sprintf(__('Rated %d out of 5 stars','noir-auto-detailing'),$item['rating'])); ?></span><span aria-hidden="true"><?php echo esc_html(str_repeat('★',$item['rating'])); ?></span></p><blockquote><p><?php echo esc_html($item['quote']); ?></p></blockquote><figcaption><span><?php echo esc_html($item['author']); ?></span><?php if ($item['attribution']!=='') : ?><span class="small-label"><?php echo esc_html($item['attribution']); ?></span><?php endif; ?></figcaption></figure><?php endforeach; ?></div></div></section><?php endif; ?>
<?php if (!empty($sections['final'])) : ?><section class="services-section home-final"><div class="container"><?php noir_section_heading($sections['final']); ?><div class="final-actions"><?php noir_appointment_link(); noir_public_contacts(); ?></div></div></section><?php endif; ?>
</main><?php get_footer(); ?>
