<?php
/** Template Name: Services */
defined('ABSPATH') || exit;
get_header();
$sections = function_exists('noir_services_page') ? noir_services_page(get_queried_object_id()) : [];
$services = function_exists('noir_services') ? noir_services() : [];
?>
<main id="main-content" class="services-main" tabindex="-1">
<section class="services-intro"><div class="container"><?php if (!empty($sections['intro'])) : $intro=$sections['intro']; ?><p class="eyebrow"><?php echo esc_html($intro['eyebrow']); ?></p><h1><?php echo esc_html($intro['heading']); ?></h1><p class="muted lead"><?php echo esc_html($intro['body']); ?></p><?php else : ?><h1><?php the_title(); ?></h1><?php endif; ?>
<?php if ($services) : ?><nav class="service-index" aria-label="<?php esc_attr_e('Service sections','noir-auto-detailing'); ?>"><?php foreach ($services as $i=>$service) : ?><a href="#service-<?php echo esc_attr($service['service_id']); ?>"><?php echo esc_html(sprintf('%02d. %s',$i+1,$service['title'])); ?></a><?php endforeach; ?></nav><?php endif; ?></div></section>
<section class="services-section"><div class="container"><?php if (!empty($sections['details'])) { noir_section_heading($sections['details']); } ?>
<div class="services-stack"><?php foreach ($services as $service) { get_template_part('template-parts/service',null,['service'=>$service]); } ?></div>
<?php if (!$services) : ?><p><?php esc_html_e('Service information is currently unavailable. Please contact the Studio for guidance.','noir-auto-detailing'); ?></p><?php noir_public_contacts(); endif; ?></div></section>
<?php if (!empty($sections['metrics'])) : ?><section class="services-section services-metrics" aria-label="<?php esc_attr_e('Studio metrics','noir-auto-detailing'); ?>"><div class="container metric-grid"><?php foreach ($sections['metrics'] as $i=>$metric) : ?><article><p class="eyebrow"><?php echo esc_html(sprintf(__('Metric %02d','noir-auto-detailing'),$i+1)); ?></p><h2><?php echo esc_html($metric['title']); ?></h2><div class="metric-value"><svg viewBox="0 0 36 36" aria-hidden="true"><circle cx="18" cy="18" r="15.9" fill="none" stroke="#353534" stroke-width="3"/><circle cx="18" cy="18" r="15.9" fill="none" stroke="currentColor" stroke-width="3" stroke-dasharray="<?php echo esc_attr([96,82,98,100][$i]??100); ?> 100" transform="rotate(-90 18 18)"/></svg><div><strong><?php echo esc_html($metric['value']); ?></strong><p class="small-label muted"><?php echo esc_html($metric['caption']); ?></p></div></div><p class="muted"><?php echo esc_html($metric['body']); ?></p></article><?php endforeach; ?></div></section><?php endif; ?>
<?php if (!empty($sections['process']['items'])) : $process=$sections['process']; ?><section class="services-section services-process"><div class="container"><?php noir_section_heading($process); ?><ol class="process-grid"><?php foreach ($process['items'] as $i=>$step) : ?><li><div class="step-top"><span aria-hidden="true"><?php echo esc_html(sprintf('%02d',$i+1)); ?></span><?php noir_icon($step['icon']); ?></div><p class="eyebrow"><?php echo esc_html(sprintf(__('Stage %d','noir-auto-detailing'),$i+1)); ?></p><h3><?php echo esc_html($step['title']); ?></h3><p class="muted"><?php echo esc_html($step['body']); ?></p></li><?php endforeach; ?></ol></div></section><?php endif; ?>
<?php if (!empty($sections['comparison']) && ($sections['comparison']['before_image'] || $sections['comparison']['after_image'])) : $comparison=$sections['comparison']; ?><section class="services-section"><div class="container"><div class="comparison-panel"><div><?php noir_section_heading($comparison); ?><?php foreach (['before','after'] as $side) : if (!$comparison[$side.'_title'] && !$comparison[$side.'_body']) { continue; } ?><div class="comparison-note <?php echo esc_attr($side); ?>"><h3 class="small-label"><?php echo esc_html($comparison[$side.'_title']); ?></h3><p class="muted"><?php echo esc_html($comparison[$side.'_body']); ?></p></div><?php endforeach; ?></div><?php get_template_part('template-parts/comparison',null,['comparison'=>$comparison]); ?></div></div></section><?php endif; ?>
<?php if (!empty($sections['faq']['items'])) : $faq=$sections['faq']; ?><section class="services-section services-faq"><div class="container faq-grid"><div><?php noir_section_heading($faq); ?><aside class="faq-assistance"><h3 class="small-label"><?php esc_html_e('Need assistance choosing a package?','noir-auto-detailing'); ?></h3><p class="muted"><?php esc_html_e('Our team can evaluate your vehicle and recommend the ideal service.','noir-auto-detailing'); ?></p><?php noir_public_contacts(); ?></aside></div><div class="faq-list"><?php foreach ($faq['items'] as $i=>$item) : ?><details<?php echo $i===0?' open':''; ?>><summary><?php echo esc_html($item['question']); ?></summary><p class="muted"><?php echo esc_html($item['answer']); ?></p></details><?php endforeach; ?></div></div></section><?php endif; ?>
<?php if (!empty($sections['final'])) : ?><section class="services-section services-final"><div class="container final-grid"><?php noir_section_heading($sections['final']); ?><div class="final-actions"><?php noir_public_contacts(); noir_appointment_link(); ?></div></div></section><?php endif; ?>
</main><?php get_footer(); ?>
